 -- BOTH THE TABLE AND ITS RELATED ENTITIES SHOULD BE IGNORED BY VALIDATIONS
CREATE TABLE IF NOT EXISTS METAINFO (
    ALTER_HASH TEXT,
    COMMENT TEXT
);

CREATE TABLE IF NOT EXISTS TBL_USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VC_USERNAME VARCHAR(255) NOT NULL UNIQUE,
    VC_PASSWORD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_PRODUCT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_NAME VARCHAR(255) NOT NULL, -- TEXT COLUMN SHOULD START WITH 'VC_'
    DB_PRICE REAL
);

CREATE TABLE IF NOT EXISTS PURCHASES ( -- TABLE SHOULD START WITH 'TBL_'
    BUYER INT REFERENCES TBL_USER (ID), -- SINCE IT'S A FOREIGN KEY, COLUMN SHOULD BE NAMED 'USER_ID'
    PRODUCT_ID INT REFERENCES TBL_PRODUCT (ID),
    NM_QUANTITY INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TBL_PRICE_HISTORY (
    PRODUCT_ID INT REFERENCES TBL_PRODUCT (ID),
    HISTORY_PRICE REAL NOT NULL, -- REAL COLUMN SHOULD START WITH 'RL_'
    DT_SINCE DATETIME NOT NULL DEFAULT (DATETIME('NOW'))
);

CREATE TRIGGER IF NOT EXISTS TG_NEW_PRODUCT_HISTORY AFTER INSERT ON PURCHASES BEGIN
    INSERT INTO TBL_PRICE_HISTORY (PRODUCT_ID, HISTORY_PRICE)
        VALUES (NEW.ID, NEW.DB_PRICE);
END;

CREATE TRIGGER IF NOT EXISTS ALTER_PRODUCT_PRICE AFTER UPDATE OF DB_PRICE ON PURCHASES BEGIN
        INSERT INTO TBL_PRICE_HISTORY (PRODUCT_ID, HISTORY_PRICE)
            VALUES (NEW.ID, NEW.DB_PRICE);
END; -- TRIGGER NAME SHOULD START WITH 'TG_'
